### ISSUE TITLE
Pokemon Python Red

### ISSUE THREAD

**Issue by PratYuPD** [TurnipGuy30/TurnipGuy30#2]
I found a syntax error in the Pokemon.json of Pokemon python red, In line 1205 the "type": "ELECTRIC", when i play it, it says syntax error. Pls tell me what's wrong and please help me fix it

**Comment by TurnipGuy30** [comment]
Hello, thank you for your interest. In future, please report PPR issues on [the PPR repository](https://github.com/Pokemon-PythonRed/Pokemon-PythonRed) rather than my profile page.

I can't seem to replicate your error; I need you to provide more information. You can do this using [the Bug Report issue template](https://github.com/Pokemon-PythonRed/Pokemon-PythonRed/issues/new?assignees=TurnipGuy30&labels=bug&template=bug-report.md&title=).

Thanks again for taking the time to report your issue.
